module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#2768A0",
        primaryDark: "#003360",
        primaryLight: "#C8E5FF",
        secondary: "#BD4C6C",
        black: "#1F2128",
        graySubtitle: "#7E7E7E",
        grayInputField: "#A4A4A4",
        grayDisableButton: "#C4C4C4",
        grayLineBased: "#F1F2F6",
        background: "#FFFFFF",
        offWhite: "#FCFCFC",
        card: "rgb(255, 255, 255)",
        text: "rgb(28, 28, 30)",
        border: "rgb(216, 216, 216)",
        notification: "rgb(255, 59, 48)",
        warning: "#F4B740",
        error: "#DF3030",
        errorLight: "#FF5050",
        successLight: "#E0FFF7",
        success: "#00BA88",
        info: "#ffd700",
        warningDark: "#946200",
        whiteGray: "#F8F8F8",
        borderGray: "#E4E6ED",
      },
    },
  },
  plugins: [],
};
