name: Cypress Tests using Cypress Docker Image

on:
  pull_request:
    branches:
      - main

concurrency: fe-e2e-test-main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.17.0-chrome106
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          build: npm run build
          start: npm run ci
          record: true
        env:
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
